- name: Remove registry, if it exists
  docker_container:
    name: "{{ registry_name }}"
    state: absent

- name: Generate fresh certs
  command: openssl req -newkey rsa:4096 -nodes -sha256 -keyout "{{ registry_cert_path }}/{{ registry_key_file }}" -x509 -days 365 -subj '/CN={{ registry_host }}' -out "{{ registry_cert_path }}/{{ registry_cert_file }}"
  when: registry_create_certs

- include: encrypt.yml
  with_items: "{{ registry_users }}" 
  
- name: Recreate secure docker registry
  docker_container:
    name: "{{ registry_name }}" 
    image: registry:2
    volumes:
      - "{{ registry_host_cert_path }}:/certs"
      - "{{ registry_host_auth_path }}:/auth"
    env:
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/{{ registry_cert_file }}"
      REGISTRY_HTTP_TLS_KEY: "/certs/{{ registry_key_file }}"
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/{{ registry_auth_file }}"
    ports:
      - "{{ registry_port }}:{{ registry_port }}"
  register: output

